import type { Metadata } from "next";
import "./globals.css";
import { CalendlyProvider } from "@/context/CalendlyContext";
import { PsychadelicBackgroundProvider } from "@/context/PsychadelicBackgroundContext";

export const metadata: Metadata = {
  title: "😸😸😸😸😸😸😸😸😸😸😸",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20,400,1,0&family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20,400,1,0&family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@20,400,1,0"
          rel="stylesheet"
        />
      </head>
      <body>
        <CalendlyProvider>
          <PsychadelicBackgroundProvider>
            <div className="flex w-full min-h-screen  h-full bg-pakistan-green justify-center">
              {children}
            </div>
          </PsychadelicBackgroundProvider>
        </CalendlyProvider>
      </body>
    </html>
  );
}
