import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CalendlyProvider } from "@/context/CalendlyContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "😸😸😸😸😸😸😸😸😸😸😸",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CalendlyProvider>
          <div className="flex w-screen h-screen bg-pakistan-green justify-center">
            {children}
          </div>
        </CalendlyProvider>
      </body>
    </html>
  );
}
